sla_app/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy


from . import views 

urlpatterns = [
    #url(r'^index/$', views.index, name='index'),
    url(r'^$', views.home, name='home'),
    url(r'^profile/$', views.CompanyDetailView.as_view(), name='profile'),
    url(r'^profile/create/$', views.CompanyCreateView.as_view(success_url=reverse_lazy('profile')), name='profile-create'),
    url(r'^profile_update/$', views.profile_update, name='profile_update'),
    #url(r'^company/(?P<user_id>\d+)/$',views.view_company,name='view_company'),
    url(r'^company/(?P<user_id>\d+)/$',views.view_company.as_view(),name='view_company'),
    url(r'^company/(?P<user_id>\d+)/service_contract/$',views.create_service_contract,name='create_service_contract'),


    url(r'^company/(?P<user_id>\d+)/service_contract/(?P<list_id>\d+)/$',views.view_list,name='slapp_view_list'),
    url(r'^company/(?P<user_id>\d+)/service_contract/(?P<list_id>\d+)/add_item$',views.add_item,name='slapp_add_item'),

    url(r'^company/(?P<user_id>\d+)/service_contract/(?P<list_id>\d+)/delete/(?P<item_id>\d+)/$',views.delete_item,name='slapp_delete_item'),

]

slapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin,auth
from django.contrib.auth import views
from tdd import urls as tdd_urls
from sla_app import urls as sla_app_urls

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy




urlpatterns = [
    url(r'^tdd/',include(tdd_urls)),
	url(r'^slapp/', include(sla_app_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth.views.login, {'template_name': 'sla_app/login.html'},name='loginslap'),
    url(r'^password_reset/$', auth.views.password_reset, {'template_name': 'sla_app/password_reset_form.html'},name='pass_reset_form_slap'),
   	url('', include('django.contrib.auth.urls')),
    url('^register/', CreateView.as_view(
            template_name='register.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('loginslap')
    ),name='registerslap'),
    url('^accounts/', include('django.contrib.auth.urls')),
]

tdd/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pag_inicio/$',views.pag_inicio,name='inicio'),
    url(r'^lists/new/$',views.new_list,name='new_list'),
    url(r'^lists/(\d+)/$',views.view_list,name='view_list'),
    url(r'^lists/(\d+)/add_item$',views.add_item,name='add_item'),

]

sla_app/models.py
from django.db import models
from django.contrib.postgres.fields import HStoreField
from django.contrib.auth.models import User


# Create your models here.



class Company(models.Model):
	#New User Field relationship has to be migrated in Django
	user = models.OneToOneField(User,on_delete=models.SET_NULL, related_name="company", null=True, blank=True)
	name=models.CharField(max_length=30,unique=True)
	service=models.TextField(max_length=200,unique=True)
	
	def __str__(self):              # __unicode__ on Python 2
		return "We are company {} that offers {}".format(self.name, self.service)

	class Meta:
		ordering = ('service','name',)

class List(models.Model):
	company = models.ForeignKey(Company)

class Item(models.Model):
    text=models.TextField(default='')
    list=models.ForeignKey(List,default=None)
    status=models.BooleanField(default=False)

class Provider(models.Model):
	name=models.CharField(max_length=30,unique=True)
	company = models.ForeignKey(Company)

	def __str__(self):              # __unicode__ on Python 2
		return "I am {} that offers {} services for company {}".format(self.name, self.company.service,self.company.name)

	class Meta:
		ordering = ('company','name',)

class Services(models.Model):
	## Migrate to deletion...unnecesary field :company = models.ForeignKey(Company)
	provider= models.ForeignKey(Provider)
	client=models.CharField(max_length=30,unique=True)
	agreement_list=HStoreField()
	status=models.BooleanField(default=False)

	def __str__(self):              # __unicode__ on Python 2
		return "I am ticket that offers {} services from company {} for client {}".format(self.provider.company.service, self.provider.company.name, self.client)

sla_app/forms.py
from django.forms import ModelForm
from sla_app.models import Company

class CompanyForm(ModelForm):
    class Meta:
        model=Company
        fields=['name','service']

sla_app/views.py
from django.shortcuts import render,redirect,resolve_url,get_object_or_404
from django.http import HttpResponse

from django.template import RequestContext, loader
from sla_app.forms import CompanyForm
from sla_app.models import Company,Item,List
from django.contrib.auth.models import User

from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

import warnings

from django.conf import settings
# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url, urlsafe_base64_decode


##To get logged in user info
from django.contrib.sessions.models import Session
from django.utils import timezone

from django.core.exceptions import ObjectDoesNotExist


def get_all_logged_in_users():
    # Query all non-expired sessions
    # use timezone.now() instead of datetime.now() in latest versions of Django
    sessions = Session.objects.filter(expire_date__gte=timezone.now())
    uid_list = []

    # Build a list of user ids from that query
    for session in sessions:
        data = session.get_decoded()
        uid_list.append(data.get('_auth_user_id', None))

    # Query all logged in users based on id list
    return User.objects.filter(id__in=uid_list)
# Create your views here.
# Create your views here.


def view_list(request,user_id,list_id):
    active_company=Company.objects.get(user__id=user_id)
    list_=List.objects.get(id=list_id,company=active_company)

    return render(request,'sla_app/create_service_contract.html', {'list':list_,'company':active_company} )

def new_list(request,user_id):
    list_=List.objects.create()
    active_company=Company.objects.get(user__id=user_id)
    Item.objects.create(text=request.POST['item_text'],list=list_)

    return redirect('/slapp/company/%d/service_contract/%d/'%(company.user.id,list_.id)) 

def add_item(request,user_id,list_id):
    active_company=Company.objects.get(user__id=user_id)
    list_=List.objects.get(id=list_id,company=active_company)
    
    Item.objects.create(text=request.POST['item_text'],list=list_)

    return redirect('/slapp/company/%d/service_contract/%d/'%(active_company.user.id,list_.id)) 

#pending to be completed
def delete_item(request,user_id,list_id,item_id):
    active_company=Company.objects.get(user__id=user_id)
    list_=List.objects.get(id=list_id,company=active_company)
    item = get_object_or_404(Item, pk=item_id).delete()
    
    return redirect('/slapp/company/%d/service_contract/%d/'%(active_company.user.id,list_.id)) 

def create_service_contract(request,user_id):
    active_company=Company.objects.get(user__id=user_id)
    try:
        #list_=List.objects.get(id=1,company=active_company)
        list_=List.objects.filter(company=active_company).order_by('pk')[0]

    except:list_=List.objects.create(company=active_company)
    #print('{!r}'.format(active_company.user.id))
    return render(request,'sla_app/create_service_contract.html',{'list':list_,'company':active_company})

def pag_inicio(request):
    return render(request,'sla_app/pagina_inicio.html',{'new_item_text':request.POST.get('item_text','')})

def home(request):
    template = loader.get_template('sla_app/home.html')
    context = RequestContext(request, {
        'test': 'test',
    })
    return HttpResponse(template.render(context))

#def profile_update(request):
#    template = loader.get_template('sla_app/profile_update.html')
#    context = RequestContext(request, {
#        'test': 'test',
#    })
#    return HttpResponse(template.render(context))

# Create your views here.

from django.views.generic import DetailView
from django.core.urlresolvers import reverse
class CompanyDetailView(DetailView):
    model = Company
    template_name = 'sla_app/company.html'

    def get_object(self):
        try:
            return self.request.user.company
        except ObjectDoesNotExist:
            return None

    def dispatch(self, request, *args, **kwargs):
        if self.get_object() is None:
            return redirect(reverse('profile-create'))
        else:
            return super(CompanyDetailView, self).dispatch(request, *args, **kwargs)

from django.views.generic import CreateView
class CompanyCreateView(CreateView):
    model = Company
    fields = ['name', 'service']

    def form_valid(self, form):
        company = form.save(commit=False)
        company.user = self.request.user
        return super(CompanyCreateView, self).form_valid(form)

    def get_absolute_url(self):
        return reverse('profile')


def profile_update(request):
    if request.method=='POST':
        new_company_name=request.POST['name']
        new_service_name=request.POST['service']
        try:
            company = request.user.company
        except ObjectDoesNotExist:
            company = Company.objects.create(user=request.user)

        company.name = new_company_name
        company.service = new_service_name

        company.save()

        return redirect('/slapp/company/%d/'%company.user.id)
    
    try:
        company = request.user.company
        return redirect('/slapp/company/%d/'%company.user.id)
    except ObjectDoesNotExist:
        new_company_name="Enter Company Name"
        new_service_name="Enter detail of service ofered"

    return render(request,
                  'sla_app/profile_update.html',
                  {'new_company_name': new_company_name, 'new_service_name': new_service_name})

#def view_company(request,user_id):
#    active_company=Company.objects.get(user__id=user_id)
#    return render(request,'sla_app/company_profile.html',{'company':active_company})

class view_company(DetailView):
    model = Company
    template_name = 'sla_app/company_profile.html'
    slug_field ='user_id'

    def get_object(self):
        try:
            return Company.objects.get(user__id=self.kwargs['user_id'])
        except ObjectDoesNotExist:
            return None

    def dispatch(self, request, *args, **kwargs):
        if self.get_object() is None:
            return redirect(reverse('profile_update'))
        else:
            return super(view_company, self).dispatch(request, *args, **kwargs)

#def profile_update(request, template_name='sla_app/profile_update.html',
#          redirect_field_name=REDIRECT_FIELD_NAME,
#          company_form=CompanyForm,
#          current_app=None, extra_context=None):
#    """
#    Displays the profile update form and handles the update action.
#    """
#    redirect_to = request.POST.get(redirect_field_name,
#                                   request.GET.get(redirect_field_name, ''))
#
#    if request.method == "POST":
#        form = company_form(data=request.POST)
#        if form.is_valid():
#
#            # Ensure the user-originating redirection url is safe.
#            if not is_safe_url(url=redirect_to, host=request.get_host()):
#                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
#
#            # Save a new Article object from the form's data.
#
#            update_profile = form.save(commit=False)
#            update_profile.user = request.user
#            update_profile.save()
#            return HttpResponseRedirect(redirect_to)
#    else:
#        form = company_form(request)
#
#    current_site = get_current_site(request)
#
#    context = {
#        'form': form,
#        redirect_field_name: redirect_to,
#        'site': current_site,
#        'site_name': current_site.name,
#    }
#    if extra_context is not None:
#        context.update(extra_context)
#
#    if current_app is not None:
#        request.current_app = current_app
#
#    return TemplateResponse(request, template_name, context)

#def index(request):
#    return HttpResponse("This will hold the SLAPP Landing Page")

sla_app/templates/sla_app/boot_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>SLAPP - Service Level Agreement APP{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="This app will help monitor, rate and review services.">
    <meta name="author" content="LeeX">



    <!-- Le styles -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <!-- Links for working locally -->
    <link href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-3.3.5-dist/css/bootstrap-theme.css' %}"
    rel="stylesheet">
    <link href="{% static 'font-awesome-4.4.0/css/font-awesome.css' %}" rel="stylesheet">

    <script src="{% static 'bootstrap-3.3.5-dist/js/jquery-1.11.3.min.js' %}" type="text/javascript"></script>

    <script src="{% static 'bootstrap-3.3.5-dist/js/bootstrap.min.js' %}" type="text/javascript"></script>

    <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
    <!-- Links for working on web -->
    <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script -->

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
    $(function(){
    {% block jquery %}
    {% endblock %}
    });
    </script>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <h2 class="brand text-center titulo">SLAPP</h2>
          <h4 class="text-center titulo"><small>The APP to rate your services</small></h4>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="messages">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <a class="close" data-dismiss="alert">×</a>
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    
    {% block content %}
    {% endblock %}
     <!-- /container -->

    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-offset-3 col-xs-6">
              <h4 class="text-muted text-center">Tell us what you think: </h4>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-offset-3 col-xs-6">
            <ul class="social list-inline text-center">
              <li><a href="mailto:leoreq@gmail.com"><i class="fa fa-envelope-square fa-2x"></i></a></li>
              <li><a href="https://github.com/leoreq"><i class="fa fa-github fa-2x"></i></a></li>
              <li><a href="https://twitter.com/leoleeex"><i class="fa fa-twitter fa-2x"></i></a></li>
             </ul>
          </div>
        </div>
        
      </div>
    </footer>
  </body>

</html>

sla_app/templates/sla_app/bootsingup.html
<div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                        <form id="loginform" class="form-horizontal" role="form">
                                    
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username or email">                                        
                                    </div>
                                
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                                    </div>
                                    

                                
                            <div class="input-group">
                                      <div class="checkbox">
                                        <label>
                                          <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                                        </label>
                                      </div>
                                    </div>


                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <a id="btn-login" href="#" class="btn btn-success">Login  </a>
                                      <a id="btn-fblogin" href="#" class="btn btn-primary">Login with Facebook</a>

                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Don't have an account! 
                                        <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                            Sign Up Here
                                        </a>
                                        </div>
                                    </div>
                                </div>    
                            </form>     



                        </div>                     
                    </div>  
        </div>
        <div id="signupbox" style="display:none; margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">Sign Up</div>
                            <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
                        </div>  
                        <div class="panel-body" >
                            <form id="signupform" class="form-horizontal" role="form">
                                
                                <div id="signupalert" style="display:none" class="alert alert-danger">
                                    <p>Error:</p>
                                    <span></span>
                                </div>
                                    
                                
                                  
                                <div class="form-group">
                                    <label for="email" class="col-md-3 control-label">Email</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="email" placeholder="Email Address">
                                    </div>
                                </div>
                                    
                                <div class="form-group">
                                    <label for="firstname" class="col-md-3 control-label">First Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="firstname" placeholder="First Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="lastname" class="col-md-3 control-label">Last Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="lastname" placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-md-3 control-label">Password</label>
                                    <div class="col-md-9">
                                        <input type="password" class="form-control" name="passwd" placeholder="Password">
                                    </div>
                                </div>
                                    
                                <div class="form-group">
                                    <label for="icode" class="col-md-3 control-label">Invitation Code</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="icode" placeholder="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <!-- Button -->                                        
                                    <div class="col-md-offset-3 col-md-9">
                                        <button id="btn-signup" type="button" class="btn btn-info"><i class="icon-hand-right"></i> &nbsp Sign Up</button>
                                        <span style="margin-left:8px;">or</span>  
                                    </div>
                                </div>
                                
                                <div style="border-top: 1px solid #999; padding-top:20px"  class="form-group">
                                    
                                    <div class="col-md-offset-3 col-md-9">
                                        <button id="btn-fbsignup" type="button" class="btn btn-primary"><i class="icon-facebook"></i>   Sign Up with Facebook</button>
                                    </div>                                           
                                        
                                </div>
                                
                                
                                
                            </form>
                         </div>
                    </div>

               
               
                
         </div> 
    </div>
    

sla_app/templates/sla_app/company.html
{% extends "sla_app/boot_base.html" %}

{% block content %}
  <h1>{{company.name}}</h1>
  <p>{{company.service}}</p>
{% endblock %}

sla_app/templates/sla_app/company_form.html
{% extends "sla_app/boot_base.html" %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Create'>
{% endblock %}

sla_app/templates/sla_app/create_service_contract.html
{% extends "sla_app/boot_base.html" %}

{% block content %}


{% if next %}
    {% if user.is_authenticated %}
    <div class="container">
        <div class="row">
            <p>Your account doesn't have access to this page. To proceed,please login with an account that has access.</p>
        </div>
    </div>

    {% else %}
    <div class="container">
        <div class="row">
            <p>Please login to see this page.</p>
        </div>
    </div>
    
    {% endif %}
{% endif %}

<div class="container text-center">
    <div class="row">
        <div class="col-xs-offset-1 col-xs-10">
            <div class="page-header">
              <h4>Create Service Contract <small></small></h4>
              <h4><small>Add all the terms of your contract</small></h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-
        12">
            <form class="form-inline" method="POST" action='/slapp/company/{{company.id}}/service_contract/{{list.id}}/add_item'>
                {%csrf_token%}
                <div class="form-group">
                    <label for="detail">Enter Service Detail</label>
                    <input type="text" class="form-control" name="item_text" id="id_new_item"  placeholder="Eg .- Product Delivered on Time.">
                </div>
                <button type="submit" class="btn btn-default">Add Contract Point</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-offset-2 col-xs-8">        
            <table id='id_list_table' class='text-center'> 
                {% for item in list.item_set.all %}
                <tr class='text-center'><td class='text-center center-block'>
                  <div class="btn-group btn-group-justified" role="group" aria-label="...">
                        <div class="btn-group" role="group">
                            <button id="{{forloop.counter}}_contract_point_id" type="button" class="btn boton text-center">
                            {{forloop.counter}}: {{ item.text }}</button>
                        </div>
                        <div class="btn-group" role="group">
                            <a href="{%url 'slapp_delete_item' company.user.id list.id item.id %}" ><button id="{{forloop.counter}}_contract_point_id_delete" type="button" class="btn  boton text-center"><span class="glyphicon glyphicon-remove"></span></button></a>
                        </div>
                    </div>
                </td></tr> 
                {% endfor %}
            </table>
        </div>
    </div>
    
    <div class="row">
        <div class="col-xs-12">
            <div class="btn-group btn-group-justified" role="group" aria-label="...">
                <div class="btn-group" role="group">
                    <a href="{%url 'view_company' company.user.id %}" ><button id="save_list_button" type="button" class="btn boton">Save and go to Profile</button></a>
                </div>
            </div>
        </div>
    </div>
</div>

{# Assumes you setup the password_reset view in your URLconf #}

<div class="container text-center">
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <p><a href="{% url 'logout' %}">Logout</a></p>  
        </div>
    </div>
</div>

{% endblock %}

sla_app/templates/sla_app/pagina_inicio.html
<html>
    <head>
        <title>To-Do lists</title>
    </head>
<body>
    <h1>Your To-Do list</h1>
    <form method="POST">
        {%csrf_token%}
       <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
    </form>

    <table id='id_list_table'> 
        {% for item in items %}
        <tr><td>1: locoloco {{ item.text }} </td></tr> 
        {% endfor %}
    </table>
</body>
</html>

sla_app/templates/sla_app/profile_update.html
{% extends "sla_app/boot_base.html" %}

{% block content %}

{% if next %}
    {% if user.is_authenticated %}
    <div class="container">
        <div class="row">
            <p>Your account doesn't have access to this page. To proceed,please login with an account that has access.</p>
        </div>
    </div>

    {% else %}
    <div class="container">
        <div class="row">
            <p>Please login to see this page.</p>
        </div>
    </div>
    
    {% endif %}
{% endif %}
<div class="container text-center">
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">

        <form id="profileupdateform" class="form-horizontal" role="form" method="post" action="{% url 'profile_update' %}">

        {% csrf_token %}

            <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="fa fa-building"></i></span>
                        <input id="id_company_name" type="text" class="form-control" name="name" value="" placeholder='{{ new_company_name }}'>                          
                    </div>

            <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="fa fa-circle-o"></i></span>
                        <input id="id_service" type="text" class="form-control" name="service" value="" placeholder="{{ new_service_name }}">                          
                    </div>
                    
            <div style="margin-top:10px" class="form-group">
                <!-- Button -->

                <div class="col-sm-12 controls">
                    <button id="updatebutton"type="submit" class="btn btn-default" value="profile_update">Update</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    
                </div>
            </div>


        </form>     
        

        </div>
    </div>
</div>

{# Assumes you setup the password_reset view in your URLconf #}

<div class="container text-center">
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
          <p>{{ request.user.username }}</p>
            <p><a href="{% url 'password_reset' %}">Lost password?</a></p>  
        </div>
    </div>
</div>

{% endblock %}